import styles from "../styles/Home.module.css";
import Head from "next/head";
import Banner from "./connectBanner";
import Footer from "./footer";
import Navbar from "./Navbar";
import { useEthers } from "@usedapp/core";
import { useState } from "react";

export default function Layout({ children }) {
  const { account } = useEthers();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Navbar />
      </header>
      <main className={styles.main}>{account ? children : <Banner />}</main>
    </div>
  );
}
